//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public int Id { get; set; }
        public string Dog1 { get; set; }
        public string Info { get; set; }
        public int Life_expectancy { get; set; }
        public string Image { get; set; }
    }
}
